const TYPES = {
	REGISTER_USER: 'REGISTER_USER',
	REGISTER_USER_FAIL: 'REGISTER_USER_FAIL',
	LOGIN_USER: 'LOGIN_USER',
	LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',
	LOAD_USER: 'LOAD_USER',
	GET_USER: 'GET_USER',
	LOGOUT: 'LOGOUT',
};

export default TYPES;
